### ISSUE TITLE
[FEATURE] Update MWAA to 2.10.1

### ISSUE THREAD

**Issue by kukushking** [awslabs/aiops-modules#254]
**Describe the solution you'd like**
- Update MWAA version to [2.10.1](https://docs.aws.amazon.com/mwaa/latest/userguide/airflow-versions.html#airflow-versions-latest)
- Update MWAA [requirements](https://github.com/awslabs/aiops-modules/blob/main/data/mwaa/requirements/requirements.txt) and [constraints](https://github.com/awslabs/aiops-modules/blob/main/data/mwaa/requirements/constraint-requirements.txt)

**Comment by EthanBunce** [comment]
Resolved with #267
